version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3978:3978"
    environment:
      - NODE_ENV=production
      - PORT=3978
      - MONGODB_URI=mongodb://mongodb:27017/supportbot
      - REDIS_URI=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./:/app
      - /app/node_modules

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
